// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "aiProvider": string;
      "aiApiKey": string;
      "aiBaseURL": string;
      "aiModel": string;
      "aiTemperature": number;
      "aiMaxTokens": number;
      "aiSystemPrompt": string;
    };
  }
}
